# Generated by Django 4.2.1 on 2023-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('mobile_operator_code', models.CharField(blank=True, max_length=10, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
    ]
